-- AlterTable
ALTER TABLE `QuoteLine` ADD COLUMN `detail` TEXT NULL,
    ADD COLUMN `discount` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `order` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `unit` VARCHAR(50) NOT NULL DEFAULT '';
